export const cuisineList = [
  "Pizza",
  "Burger",
  "Salad",
  "Yogurt",
  "Hotdog",
  "Pie",
  "Sandwitch",
  "Cafe",
  "Chinese",
  "French",
  "Breakfast",
  "American",
  "BBQ",
  "Healthy",
  "Italian",
  "Japanese",
  "Chinese",
  "French",
  "Greek",
  "Desserts",
  "Pancakes",
  "Turkish",
  "Irish Breakfast",
  "Coffee",
];
//Creates a list of filters that are used for the application.
